CREATE TRIGGER TGR_TBAREA
ON TBAREA
INSTEAD OF INSERT 
AS
BEGIN
	IF EXISTS (SELECT 1 FROM INSERTED WHERE DATACRIACAO > CURRENT_TIMESTAMP)
	BEGIN 
		RAISERROR('NÃO É POSSÍVEL INSERIR OS DADOS POIS A DATACRIACAO DEVE SER MENOR QUE A DATA ATUAL.',1,1)
	END
END

INSERT INTO TBAREA(CODTIPOAREA,DESCAREA,DATACRIACAO,ATIVO) VALUES (1,'AREA CORTADA','18-06-2023','NAO')
DELETE FROM TBAREA WHERE CODAREA = 18
SELECT * FROM TBAREA  