CREATE PROCEDURE P_INSERT_TBTIPOAREA
	@DESCTIPOAREA VARCHAR(200) ,
	@ATIVO CHAR(10)
AS 
BEGIN
INSERT INTO TBTIPOAREA (DESCTIPOAREA,ATIVO) VALUES(@DESCTIPOAREA,@ATIVO)
END

CREATE PROCEDURE P_UPDATE_TBTIPOAREA
	@CODTIPOAREA INT,
	@DESCTIPOAREA VARCHAR(200) ,
	@ATIVO CHAR(10)
AS 
BEGIN
UPDATE TBTIPOAREA SET DESCTIPOAREA = @DESCTIPOAREA, ATIVO = @ATIVO
WHERE CODTIPOAREA = @CODTIPOAREA
END

CREATE PROCEDURE P_DELETE_TBTIPOAREA
	@CODTIPOAREA INT
AS 
BEGIN
DELETE FROM TBTIPOAREA WHERE CODTIPOAREA = @CODTIPOAREA
END

EXEC P_INSERT_TBTIPOAREA 'ALEATORIA', 'SIM'

EXEC P_UPDATE_TBTIPOAREA '3','PINUS', 'NAO'

EXEC P_DELETE_TBTIPOAREA '6'
SELECT * FROM TBTIPOAREA
